openapi: 3.0.3
info:
  title: API Integrador
  version: 1.0.0
  description: API de autenticación y recursos del taller

servers:
  - url: http://localhost:3001/api
    description: Servidor local

paths:
  /api/auth/login:
    post:
      tags:
        - Auth
      summary: Iniciar sesión
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Autenticación exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          description: Faltan credenciales
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Credenciales inválidas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    LoginRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          example: francisco
        password:
          type: string
          example: contraseña123

    LoginResponse:
      type: object
      properties:
        token:
          type: string
          description: JSON Web Token para futuros requests
        username:
          type: string
          description: Nombre de usuario autenticado
        role:
          type: string
          description: Rol del usuario ("administrador" o "empleado")
      example:
        token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        username: francisco
        role: administrador

    Error:
      type: object
      properties:
        message:
          type: string
      example:
        message: Credenciales inválidas
