paths:
  /api/barrios:
    get:
      tags:
        - Barrio
      summary: Obtener todos los barrios
      parameters:
        - in: query
          name: search
          schema:
            type: string
      responses:
        '200':
          description: Lista de barrios
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Barrio'
    post:
      tags:
        - Barrio
      summary: Crear un nuevo barrio
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BarrioInput'
      responses:
        '201':
          description: Barrio creado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Barrio'
  /api/barrios/paginado:
    get:
      tags:
        - Barrio
      summary: Obtener barrios paginados
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
        - in: query
          name: search
          schema:
            type: string
      responses:
        '200':
          description: Resultados paginados
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Barrio'
                  page:
                    type: integer
                  totalPages:
                    type: integer
                  totalCount:
                    type: integer
  /api/barrios/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
    get:
      tags:
        - Barrio
      summary: Obtener barrio por ID
      responses:
        '200':
          description: Barrio encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Barrio'
        '404':
          description: No encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - Barrio
      summary: Actualizar barrio
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BarrioInput'
      responses:
        '200':
          description: Barrio actualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Barrio'
        '404':
          description: No encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - Barrio
      summary: Eliminar barrio
      responses:
        '204':
          description: Eliminado
        '404':
          description: No encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Barrio:
      type: object
      properties:
        _id:
          type: string
        nombre_barrio:
          type: string
        id_distrito:
          type: string
      required:
        - _id
        - nombre_barrio
        - id_distrito
    BarrioInput:
      type: object
      properties:
        nombre_barrio:
          type: string
        id_distrito:
          type: string
      required:
        - nombre_barrio
        - id_distrito
    Error:
      type: object
      properties:
        message:
          type: string
      required:
        - message
