paths:
  /api/clienteinformaciones:
    get:
      tags:
        - ClienteInformacion
      summary: Obtener todas las informaciones de cliente
      parameters:
        - in: query
          name: search
          schema:
            type: string
          description: Filtrar por id_cliente o id_tipo_cliente
      responses:
        '200':
          description: Lista de informaciones de cliente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClienteInformacion'
    post:
      tags:
        - ClienteInformacion
      summary: Crear una nueva información de cliente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClienteInformacionInput'
      responses:
        '201':
          description: Información creada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClienteInformacion'
  /api/clienteinformaciones/paginado:
    get:
      tags:
        - ClienteInformacion
      summary: Informaciones de cliente paginadas
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
        - in: query
          name: search
          schema:
            type: string
          description: Filtrar por id_cliente o id_tipo_cliente
      responses:
        '200':
          description: Resultado paginado
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/ClienteInformacion'
                  page:
                    type: integer
                  totalPages:
                    type: integer
                  totalCount:
                    type: integer
  /api/clienteinformaciones/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
    get:
      tags:
        - ClienteInformacion
      summary: Obtener información de cliente por ID
      responses:
        '200':
          description: Información encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClienteInformacion'
        '404':
          description: No encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - ClienteInformacion
      summary: Actualizar información de cliente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClienteInformacionInput'
      responses:
        '200':
          description: Información actualizada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClienteInformacion'
        '404':
          description: No encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - ClienteInformacion
      summary: Eliminar información de cliente
      responses:
        '204':
          description: Eliminado
        '404':
          description: No encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    ClienteInformacion:
      type: object
      properties:
        _id:
          type: string
        id_cliente:
          type: string
        id_tipo_cliente:
          type: string
      required:
        - _id
        - id_cliente
        - id_tipo_cliente

    ClienteInformacionInput:
      type: object
      properties:
        id_cliente:
          type: string
        id_tipo_cliente:
          type: string
      required:
        - id_cliente
        - id_tipo_cliente

    Error:
      type: object
      properties:
        message:
          type: string
      required:
        - message
