paths:
  /api/facturas:
    get:
      tags:
        - Factura
      summary: Obtener todas las facturas
      parameters:
        - in: query
          name: search
          schema:
            type: string
          description: Filtrar por id_reparacion, id_empleado o id_metodo_pago
      responses:
        '200':
          description: Lista de facturas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Factura'
    post:
      tags:
        - Factura
      summary: Crear una nueva factura
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FacturaInput'
      responses:
        '201':
          description: Factura creada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Factura'
  /api/facturas/paginado:
    get:
      tags:
        - Factura
      summary: Facturas paginadas
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
        - in: query
          name: search
          schema:
            type: string
          description: Filtrar por id_reparacion, id_empleado o id_metodo_pago
      responses:
        '200':
          description: Resultado paginado de facturas
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Factura'
                  page:
                    type: integer
                  totalPages:
                    type: integer
                  totalCount:
                    type: integer
  /api/facturas/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
    get:
      tags:
        - Factura
      summary: Obtener factura por ID
      responses:
        '200':
          description: Factura encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Factura'
        '404':
          description: No encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - Factura
      summary: Actualizar factura
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FacturaInput'
      responses:
        '200':
          description: Factura actualizada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Factura'
        '404':
          description: No encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - Factura
      summary: Eliminar factura
      responses:
        '204':
          description: Eliminado
        '404':
          description: No encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Factura:
      type: object
      properties:
        _id:
          type: string
        id_reparacion:
          type: string
        id_empleado:
          type: string
        fecha:
          type: string
          format: date-time
        sub_total:
          type: number
        descuento:
          type: number
        total:
          type: number
        id_metodo_pago:
          type: string
      required:
        - _id
        - id_reparacion
        - id_empleado
        - fecha
        - sub_total
        - descuento
        - total
        - id_metodo_pago

    FacturaInput:
      type: object
      properties:
        id_reparacion:
          type: string
        id_empleado:
          type: string
        sub_total:
          type: number
        descuento:
          type: number
        total:
          type: number
        id_metodo_pago:
          type: string
      required:
        - id_reparacion
        - id_empleado
        - sub_total
        - descuento
        - total
        - id_metodo_pago

    Error:
      type: object
      properties:
        message:
          type: string
      required:
        - message
