paths:
  /api/metodospagos:
    get:
      tags:
        - MetodoPago
      summary: Obtener todos los métodos de pago
      parameters:
        - in: query
          name: search
          schema:
            type: string
          description: Filtrar por nombre o ID de método
      responses:
        '200':
          description: Lista de métodos de pago
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MetodoPago'
    post:
      tags:
        - MetodoPago
      summary: Crear un método de pago
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MetodoPagoInput'
      responses:
        '201':
          description: Método de pago creado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetodoPago'

  /api/metodospagos/paginado:
    get:
      tags:
        - MetodoPago
      summary: Métodos de pago paginados
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
        - in: query
          name: search
          schema:
            type: string
          description: Filtrar por nombre o ID de método
      responses:
        '200':
          description: Resultado paginado de métodos de pago
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/MetodoPago'
                  page:
                    type: integer
                  totalPages:
                    type: integer
                  totalCount:
                    type: integer

  /api/metodospagos/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
    get:
      tags:
        - MetodoPago
      summary: Obtener un método de pago por ID
      responses:
        '200':
          description: Método de pago encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetodoPago'
        '404':
          description: No encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - MetodoPago
      summary: Actualizar un método de pago
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MetodoPagoInput'
      responses:
        '200':
          description: Método de pago actualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetodoPago'
        '404':
          description: No encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - MetodoPago
      summary: Eliminar un método de pago
      responses:
        '204':
          description: Eliminado exitosamente
        '404':
          description: No encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    MetodoPago:
      type: object
      properties:
        _id:
          type: string
        id_metodo_pago:
          type: integer
        nombre_metodo:
          type: string
        id_tipo_pago:
          type: string
      required:
        - _id
        - id_metodo_pago
        - nombre_metodo

    MetodoPagoInput:
      type: object
      properties:
        id_metodo_pago:
          type: integer
        nombre_metodo:
          type: string
        id_tipo_pago:
          type: string
      required:
        - id_metodo_pago
        - nombre_metodo

    Error:
      type: object
      properties:
        message:
          type: string
      required:
        - message
