paths:
  /api/clientes:
    get:
      tags:
        - Cliente
      summary: Obtener todas las clientes
      parameters:
        - in: query
          name: search
          schema:
            type: string
          description: Filtrar por nombre, cédula, correo o teléfono
      responses:
        '200':
          description: Lista de clientes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cliente'
    post:
      tags:
        - Cliente
      summary: Crear una nueva cliente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonaInput'
      responses:
        '201':
          description: Cliente creada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cliente'
  /api/clientes/paginado:
    get:
      tags:
        - Cliente
      summary: Personas paginadas
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
        - in: query
          name: search
          schema:
            type: string
          description: Filtrar por nombre, cédula, correo o teléfono
      responses:
        '200':
          description: Resultado paginado de clientes
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Cliente'
                  page:
                    type: integer
                  totalPages:
                    type: integer
                  totalCount:
                    type: integer
  /api/clientes/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
    get:
      tags:
        - Cliente
      summary: Obtener cliente por ID
      responses:
        '200':
          description: Cliente encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cliente'
        '404':
          description: No encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - Cliente
      summary: Actualizar cliente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonaInput'
      responses:
        '200':
          description: Cliente actualizada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cliente'
        '404':
          description: No encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - Cliente
      summary: Eliminar cliente
      responses:
        '204':
          description: Eliminado exitosamente
        '404':
          description: No encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Cliente:
      type: object
      properties:
        _id:
          type: string
        cedula:
          type: string
        rnc:
          type: string
        nombre:
          type: string
        numero_telefono:
          type: string
        correo:
          type: string
        id_barrio:
          type: string
      required:
        - nombre
        - numero_telefono
        - correo

    PersonaInput:
      type: object
      properties:
        cedula:
          type: string
        rnc:
          type: string
        nombre:
          type: string
        numero_telefono:
          type: string
        correo:
          type: string
        id_barrio:
          type: string
      required:
        - nombre
        - numero_telefono
        - correo

    Error:
      type: object
      properties:
        message:
          type: string
      required:
        - message
