paths:
  /api/provincias:
    get:
      tags:
        - Provincia
      summary: Obtener todas las provincias
      parameters:
        - in: query
          name: search
          schema:
            type: string
          description: Filtrar por nombre_provincia
      responses:
        '200':
          description: Lista de provincias
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Provincia'
    post:
      tags:
        - Provincia
      summary: Crear una nueva provincia
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProvinciaInput'
      responses:
        '201':
          description: Provincia creada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Provincia'
  /api/provincias/paginado:
    get:
      tags:
        - Provincia
      summary: Provincias paginadas
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
        - in: query
          name: search
          schema:
            type: string
          description: Filtrar por nombre_provincia
      responses:
        '200':
          description: Resultado paginado de provincias
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Provincia'
                  page:
                    type: integer
                  totalPages:
                    type: integer
                  totalCount:
                    type: integer
  /api/provincias/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
    get:
      tags:
        - Provincia
      summary: Obtener provincia por ID
      responses:
        '200':
          description: Provincia encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Provincia'
        '404':
          description: No encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - Provincia
      summary: Actualizar provincia
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProvinciaInput'
      responses:
        '200':
          description: Provincia actualizada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Provincia'
        '404':
          description: No encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - Provincia
      summary: Eliminar provincia
      responses:
        '204':
          description: Eliminado exitosamente
        '404':
          description: No encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Provincia:
      type: object
      properties:
        _id:
          type: string
        nombre_provincia:
          type: string
      required:
        - _id
        - nombre_provincia

    ProvinciaInput:
      type: object
      properties:
        nombre_provincia:
          type: string
      required:
        - nombre_provincia

    Error:
      type: object
      properties:
        message:
          type: string
      required:
        - message
