paths:
  /api/recepcionvehiculos:
    get:
      tags:
        - RecepcionVehiculo
      summary: Obtener todas las recepciones de vehículo
      parameters:
        - in: query
          name: search
          schema:
            type: string
          description: Filtrar por empleado, vehículo, comentario o resultado
      responses:
        '200':
          description: Lista de recepciones
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RecepcionVehiculo'
    post:
      tags:
        - RecepcionVehiculo
      summary: Crear una nueva recepción de vehículo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecepcionVehiculoInput'
      responses:
        '201':
          description: Recepción creada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecepcionVehiculo'
  /api/recepcionvehiculos/paginado:
    get:
      tags:
        - RecepcionVehiculo
      summary: Recepciones de vehículo paginadas
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
        - in: query
          name: search
          schema:
            type: string
          description: Filtrar por empleado, vehículo, comentario o resultado
      responses:
        '200':
          description: Resultado paginado de recepciones
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/RecepcionVehiculo'
                  page:
                    type: integer
                  totalPages:
                    type: integer
                  totalCount:
                    type: integer
  /api/recepcionvehiculos/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
    get:
      tags:
        - RecepcionVehiculo
      summary: Obtener recepción por ID
      responses:
        '200':
          description: Recepción encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecepcionVehiculo'
        '404':
          description: No encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - RecepcionVehiculo
      summary: Actualizar recepción de vehículo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecepcionVehiculoInput'
      responses:
        '200':
          description: Recepción actualizada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecepcionVehiculo'
        '404':
          description: No encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - RecepcionVehiculo
      summary: Eliminar recepción de vehículo
      responses:
        '204':
          description: Eliminado exitosamente
        '404':
          description: No encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    RecepcionVehiculo:
      type: object
      properties:
        _id:
          type: string
        id_empleado:
          type: string
        id_vehiculo:
          type: string
        comentario:
          type: string
        fecha:
          type: string
          format: date-time
        problema_reportado:
          type: string
      required:
        - _id
        - id_empleado
        - id_vehiculo
        - fecha

    RecepcionVehiculoInput:
      type: object
      properties:
        id_empleado:
          type: string
        id_vehiculo:
          type: string
        comentario:
          type: string
        problema_reportado:
          type: string
      required:
        - id_empleado
        - id_vehiculo

    Error:
      type: object
      properties:
        message:
          type: string
      required:
        - message
