paths:
  /api/reparacionvehiculos:
    get:
      tags:
        - ReparacionVehiculo
      summary: Obtener todas las reparaciones de vehículo
      parameters:
        - in: query
          name: search
          schema:
            type: string
          description: Filtrar por inspección, empleado o descripción
      responses:
        '200':
          description: Lista de reparaciones
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ReparacionVehiculo'
    post:
      tags:
        - ReparacionVehiculo
      summary: Crear una nueva reparación de vehículo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReparacionVehiculoInput'
      responses:
        '201':
          description: Reparación creada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReparacionVehiculo'
  /api/reparacionvehiculos/paginado:
    get:
      tags:
        - ReparacionVehiculo
      summary: Reparaciones paginadas
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
        - in: query
          name: search
          schema:
            type: string
          description: Filtrar por inspección, empleado o descripción
      responses:
        '200':
          description: Resultado paginado de reparaciones
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/ReparacionVehiculo'
                  page:
                    type: integer
                  totalPages:
                    type: integer
                  totalCount:
                    type: integer
  /api/reparacionvehiculos/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
    get:
      tags:
        - ReparacionVehiculo
      summary: Obtener reparación por ID
      responses:
        '200':
          description: Reparación encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReparacionVehiculo'
        '404':
          description: No encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - ReparacionVehiculo
      summary: Actualizar reparación
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReparacionVehiculoInput'
      responses:
        '200':
          description: Reparación actualizada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReparacionVehiculo'
        '404':
          description: No encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - ReparacionVehiculo
      summary: Eliminar reparación
      responses:
        '204':
          description: Eliminado exitosamente
        '404':
          description: No encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    ReparacionVehiculo:
      type: object
      properties:
        _id:
          type: string
        id_inspeccion:
          type: string
        id_empleado:
          type: string
        fecha_inicio:
          type: string
          format: date-time
        fecha_fin:
          type: string
          format: date-time
        descripcion:
          type: string
        costo_total:
          type: number
      required:
        - _id
        - id_inspeccion
        - id_empleado
        - fecha_inicio
        - descripcion

    ReparacionVehiculoInput:
      type: object
      properties:
        id_inspeccion:
          type: string
        id_empleado:
          type: string
        descripcion:
          type: string
        fecha_fin:
          type: string
          format: date-time
        costo_total:
          type: number
      required:
        - id_inspeccion
        - id_empleado
        - descripcion

    Error:
      type: object
      properties:
        message:
          type: string
      required:
        - message
