paths:
  /api/tipospiezas:
    get:
      tags:
        - TipoPieza
      summary: Obtener todos los tipos de pieza
      parameters:
        - in: query
          name: search
          schema:
            type: string
          description: Filtrar por nombre_tipo
      responses:
        '200':
          description: Lista de tipos de pieza
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TipoPieza'
    post:
      tags:
        - TipoPieza
      summary: Crear un nuevo tipo de pieza
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TipoPiezaInput'
      responses:
        '201':
          description: Tipo de pieza creado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TipoPieza'
  /api/tipospiezas/paginado:
    get:
      tags:
        - TipoPieza
      summary: Tipos de pieza paginados
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
        - in: query
          name: search
          schema:
            type: string
          description: Filtrar por nombre_tipo
      responses:
        '200':
          description: Resultado paginado de tipos de pieza
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/TipoPieza'
                  page:
                    type: integer
                  totalPages:
                    type: integer
                  totalCount:
                    type: integer
  /api/tipospiezas/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
    get:
      tags:
        - TipoPieza
      summary: Obtener tipo de pieza por ID
      responses:
        '200':
          description: Tipo de pieza encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TipoPieza'
        '404':
          description: No encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - TipoPieza
      summary: Actualizar tipo de pieza
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TipoPiezaInput'
      responses:
        '200':
          description: Tipo de pieza actualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TipoPieza'
        '404':
          description: No encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - TipoPieza
      summary: Eliminar tipo de pieza
      responses:
        '204':
          description: Eliminado exitosamente
        '404':
          description: No encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    TipoPieza:
      type: object
      properties:
        _id:
          type: string
        nombre_tipo:
          type: string
      required:
        - _id
        - nombre_tipo

    TipoPiezaInput:
      type: object
      properties:
        nombre_tipo:
          type: string
      required:
        - nombre_tipo

    Error:
      type: object
      properties:
        message:
          type: string
      required:
        - message
