import { Router } from "express";
import marcaVehiculosRoutes from "./marcaVehiculosRoutes";
import coloresDatosRoutes from "./coloresDatosRoutes";
import empleadoInformacionRoutes from "./empleadoInformacionRoutes";
import facturaRoutes from "./facturaRoutes";
import garantiaRoutes from "./garantiaRoutes";
import inspeccionVehiculoRoutes from "./inspeccionVehiculoRoutes";
import metodoPagoRoutes from "./metodoPagoRoutes";
import modelosDatosRoutes from "./modelosDatosRoutes";
import clienesRoutes from "./clienetRoutes";
import piezaInventarioRoutes from "./piezaInventarioRoutes";
import recepcionVehiculoRoutes from "./recepcionVehiculoRoutes";
import reciboVehiculoRoutes from "./reciboVehiculoRoutes";
import reparacionVehiculoRoutes from "./reparacionVehiculoRoutes";
import suplidorPiezaRoutes from "./suplidorPiezaRoutes";
import suplidorPiezaRelacionRoutes from "./suplidorPiezaRelacionRoutes";
import usuariosRoutes from "./usuariosRoutes";
import vehiculoDatosRoutes from "./vehiculoDatosRoutes";
import tipoPagosRoutes from "./tipoPagosRoutes";
import authRoutes from "./authRoutes";
import ubicacionesRoutes from "./ubicacionesRoutes";
import historialCompraRoutes from "./historialCompraRoutes";
import piezaUsadaRoutes from "./piezaUsadaRoutes";
import pagoFacturaRoutes from "./pagoFacturaRoutes";

const router = Router();

router.use(coloresDatosRoutes);
router.use(empleadoInformacionRoutes);
router.use(facturaRoutes);
router.use(garantiaRoutes);
router.use(inspeccionVehiculoRoutes);
router.use(marcaVehiculosRoutes);
router.use(metodoPagoRoutes);
router.use(modelosDatosRoutes);
router.use(clienesRoutes);
router.use(piezaInventarioRoutes);
router.use(recepcionVehiculoRoutes);
router.use(reciboVehiculoRoutes);
router.use(reparacionVehiculoRoutes);
router.use(suplidorPiezaRelacionRoutes);
router.use(suplidorPiezaRoutes);
router.use(tipoPagosRoutes);
router.use(usuariosRoutes);
router.use(vehiculoDatosRoutes);
router.use('/auth', authRoutes);
router.use(ubicacionesRoutes);
router.use(historialCompraRoutes);
router.use(piezaUsadaRoutes);
router.use(pagoFacturaRoutes);

export default router;