paths:
  /api/garantias:
    get:
      tags:
        - Garantia
      summary: Obtener todas las garantías
      parameters:
        - in: query
          name: search
          schema:
            type: string
          description: Filtrar por id_reparacion, id_empleado o tipo_garantia
      responses:
        '200':
          description: Lista de garantías
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Garantia'
    post:
      tags:
        - Garantia
      summary: Crear una garantía
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GarantiaInput'
      responses:
        '201':
          description: Garantía creada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Garantia'
  /api/garantias/paginado:
    get:
      tags:
        - Garantia
      summary: Garantías paginadas
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
        - in: query
          name: search
          schema:
            type: string
          description: Filtrar por id_reparacion, id_empleado o tipo_garantia
      responses:
        '200':
          description: Resultado paginado de garantías
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Garantia'
                  page:
                    type: integer
                  totalPages:
                    type: integer
                  totalCount:
                    type: integer
  /api/garantias/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
    get:
      tags:
        - Garantia
      summary: Obtener garantía por ID
      responses:
        '200':
          description: Garantía encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Garantia'
        '404':
          description: No encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - Garantia
      summary: Actualizar garantía
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GarantiaInput'
      responses:
        '200':
          description: Garantía actualizada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Garantia'
        '404':
          description: No encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - Garantia
      summary: Eliminar garantía
      responses:
        '204':
          description: Eliminado
        '404':
          description: No encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Garantia:
      type: object
      properties:
        _id:
          type: string
        id_reparacion:
          type: string
        id_empleado:
          type: string
        fecha_inicio:
          type: string
          format: date-time
        fecha_expiracion:
          type: string
          format: date-time
        tipo_garantia:
          type: string
        descripcion:
          type: string
      required:
        - _id
        - id_reparacion
        - id_empleado
        - fecha_inicio
        - fecha_expiracion
        - tipo_garantia

    GarantiaInput:
      type: object
      properties:
        id_reparacion:
          type: string
        id_empleado:
          type: string
        fecha_expiracion:
          type: string
          format: date-time
        tipo_garantia:
          type: string
        descripcion:
          type: string
      required:
        - id_reparacion
        - id_empleado
        - fecha_expiracion
        - tipo_garantia

    Error:
      type: object
      properties:
        message:
          type: string
      required:
        - message
