paths:
  /api/suplidorpiezas:
    get:
      tags:
        - SuplidorPieza
      summary: Obtener todos los suplidores de pieza
      parameters:
        - in: query
          name: search
          schema:
            type: string
          description: Filtrar por id_cliente
      responses:
        '200':
          description: Lista de suplidores de pieza
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SuplidorPieza'
    post:
      tags:
        - SuplidorPieza
      summary: Crear un nuevo suplidor de pieza
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SuplidorPiezaInput'
      responses:
        '201':
          description: SuplidorPieza creada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuplidorPieza'
  /api/suplidorpiezas/paginado:
    get:
      tags:
        - SuplidorPieza
      summary: Suplidores de pieza paginados
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
        - in: query
          name: search
          schema:
            type: string
          description: Filtrar por id_cliente
      responses:
        '200':
          description: Resultado paginado de suplidores de pieza
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/SuplidorPieza'
                  page:
                    type: integer
                  totalPages:
                    type: integer
                  totalCount:
                    type: integer
  /api/suplidorpiezas/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
    get:
      tags:
        - SuplidorPieza
      summary: Obtener suplidor de pieza por ID
      responses:
        '200':
          description: SuplidorPieza encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuplidorPieza'
        '404':
          description: No encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - SuplidorPieza
      summary: Actualizar suplidor de pieza
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SuplidorPiezaInput'
      responses:
        '200':
          description: SuplidorPieza actualizada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuplidorPieza'
        '404':
          description: No encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - SuplidorPieza
      summary: Eliminar suplidor de pieza
      responses:
        '204':
          description: Eliminado exitosamente
        '404':
          description: No encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    SuplidorPieza:
      type: object
      properties:
        _id:
          type: string
        id_cliente:
          type: string
      required:
        - _id
        - id_cliente

    SuplidorPiezaInput:
      type: object
      properties:
        id_cliente:
          type: string
      required:
        - id_cliente

    Error:
      type: object
      properties:
        message:
          type: string
      required:
        - message
